### ISSUE TITLE
Вопрос

### ISSUE THREAD

**Issue by Daaamir2** [Daaamir2/Dictionary#1]
Хотел бы узнать, можно ли так писать отображения элементов OneToMany
https://github.com/Daaamir2/Dictionary/blob/a98cfe9ca1425d66278830cc9115080df7fab704/src/main/java/ru/itpark/dictionary/controller/DictionaryController.java#L33-L38
https://github.com/Daaamir2/Dictionary/blob/a98cfe9ca1425d66278830cc9115080df7fab704/src/main/java/ru/itpark/dictionary/service/DictionaryService.java#L28-L32

я имею ввиду данную строку 
https://github.com/Daaamir2/Dictionary/blob/a98cfe9ca1425d66278830cc9115080df7fab704/src/main/java/ru/itpark/dictionary/controller/DictionaryController.java#L36

если нет, то я хотел бы узнать, как из доставать значения которые принадлежат именно требуемому объекту, а не всему репозиторию(в моем случае WordRepository)

**Comment by coursar** [comment]
Строку можно, ничего вам не мешает это сделать
