### ISSUE TITLE
Вопрос 3

### ISSUE THREAD

**Issue by Daaamir2** [Daaamir2/Dictionary#3]
почему данный код выполняется, но только один раз (т.е. если зайти в edit и что то исправить первый раз все сохранится, но при повторном исправлении слова выдает ошибку), тоже самое с удаление, если сначала исправить слово, то потом удалить его невозможно
https://github.com/Daaamir2/Dictionary/blob/bf76c608513124dbc6e1a738f7b0651dd0db82e9/src/main/java/ru/itpark/dictionary/service/DictionaryService.java#L65-L81

**Comment by coursar** [comment]
надо разбираться, почему он у вас выполняется только один раз ))
